### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'put'

### ISSUE THREAD

**Issue by GbengaOdesanmi** [rllab/rllab#248]
python maml_trpo_point.py 
python3 /home/gbenga/Documents/2019vrepcode/maml_rl-master/scripts/run_experiment_lite.py  --n_parallel '1'  --snapshot_mode 'last'  --seed '1'  --plot 'False'  --exp_name 'trpomaml1_fbs20_mbs40_flr_0.5metalr_0.01_step11'  --log_dir '/home/gbenga/Documents/2019vrepcode/maml_rl-master/data/local/vpg-maml-point100/trpomaml1_fbs20_mbs40_flr_0.5metalr_0.01_step11'  --use_cloudpickle 'False'  --args_data 'gANjcmxsYWIubWlzYy5pbnN0cnVtZW50ClN0dWJNZXRob2RDYWxsCnEAKYFxAX1xAihYBgAAAF9fYXJnc3EDKGNybGxhYi5taXNjLmluc3RydW1lbnQKU3R1Yk9iamVjdApxBCmBcQV9cQYoWAQAAABhcmdzcQcpWAYAAABrd2FyZ3NxCH1xCShYAwAAAGVudnEKaAQpgXELfXEMKGgHKWgIfXENWAsAAAB3cmFwcGVkX2VudnEOaAQpgXEPfXEQKGgHKWgIfXERaApoBCmBcRJ9cRMoaAcpaAh9cRRYCwAAAHByb3h5X2NsYXNzcRVjbWFtbF9leGFtcGxlcy5wb2ludF9lbnZfcmFuZGdvYWwKUG9pbnRFbnZSYW5kR29hbApxFnVic2gVY3JsbGFiLmVudnMubm9ybWFsaXplZF9lbnYKTm9ybWFsaXplZEVudgpxF3Vic2gVY3NhbmRib3gucm9ja3kudGYuZW52cy5iYXNlClRmRW52CnEYdWJYBgAAAHBvbGljeXEZaAQpgXEafXEbKGgHKWgIfXEcKFgEAAAAbmFtZXEdaBlYCAAAAGVudl9zcGVjcR5jcmxsYWIubWlzYy5pbnN0cnVtZW50ClN0dWJBdHRyCnEfKYFxIH1xIShYBAAAAF9vYmpxImgLWAoAAABfYXR0cl9uYW1lcSNYBAAAAHNwZWNxJHViWA4AAABncmFkX3N0ZXBfc2l6ZXElRz/gAAAAAAAAWBMAAABoaWRkZW5fbm9ubGluZWFyaXR5cSZjdGVuc29yZmxvdy5weXRob24ub3BzLmdlbl9ubl9vcHMKcmVsdQpxJ1gMAAAAaGlkZGVuX3NpemVzcShLZEtkhnEpdWgVY3NhbmRib3gucm9ja3kudGYucG9saWNpZXMubWFtbF9taW5pbWFsX2dhdXNzX21scF9wb2xpY3kKTUFNTEdhdXNzaWFuTUxQUG9saWN5CnEqdWJYCAAAAGJhc2VsaW5lcStoBCmBcSx9cS0oaAcpaAh9cS5oHmgfKYFxL31xMChoImgLaCNoJHVic2gVY3JsbGFiLmJhc2VsaW5lcy5saW5lYXJfZmVhdHVyZV9iYXNlbGluZQpMaW5lYXJGZWF0dXJlQmFzZWxpbmUKcTF1YlgKAAAAYmF0Y2hfc2l6ZXEySxRYDwAAAG1heF9wYXRoX2xlbmd0aHEzS2RYDwAAAG1ldGFfYmF0Y2hfc2l6ZXE0SyhYEAAAAG51bV9ncmFkX3VwZGF0ZXNxNUsBWAUAAABuX2l0cnE2S2RYCAAAAHVzZV9tYW1scTeIWAkAAABzdGVwX3NpemVxOEc/hHrhR64Ue1gEAAAAcGxvdHE5iHVoFWNzYW5kYm94LnJvY2t5LnRmLmFsZ29zLm1hbWxfdHJwbwpNQU1MVFJQTwpxOnViWAUAAAB0cmFpbnE7KX1xPHRxPVgIAAAAX19rd2FyZ3NxPn1xP3ViLg=='
using seed 1
2019-03-04 09:53:30.686207 CST | Setting seed to 1
using seed 1
WARNING:tensorflow:From /home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-03-04 09:53:31.209170: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-04 09:53:31.232905: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3591920000 Hz
2019-03-04 09:53:31.233243: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x558f20a647b0 executing computations on platform Host. Devices:
2019-03-04 09:53:31.233272: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /home/gbenga/Downloads/abiona1008/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Traceback (most recent call last):
  File "/home/gbenga/Documents/2019vrepcode/maml_rl-master/scripts/run_experiment_lite.py", line 136, in <module>
    run_experiment(sys.argv)
  File "/home/gbenga/Documents/2019vrepcode/maml_rl-master/scripts/run_experiment_lite.py", line 123, in run_experiment
    maybe_iter = concretize(data)
  File "./rllab/misc/instrument.py", line 1214, in concretize
    return method(*args, **kwargs)
  File "./sandbox/rocky/tf/algos/batch_maml_polopt.py", line 150, in train
    self.start_worker()
  File "./sandbox/rocky/tf/algos/batch_maml_polopt.py", line 114, in start_worker
    plotter.init_plot(self.env, self.policy)
  File "./rllab/plotter/plotter.py", line 67, in init_plot
    queue.put(['update', env, policy])
AttributeError: 'NoneType' object has no attribute 'put'

**Comment by ZhuFengdaaa** [comment]
Just like [here](https://github.com/rll/rllab/blob/master/examples/trpo_cartpole_pickled.py) line 30 and line 44, you need to add `plot=True` for both.
