### ISSUE TITLE
Error while instantiating <class 'rllab.envs.gym_env.GymEnv'>

### ISSUE THREAD

**Issue by kibamin** [rllab/rllab#254]
Hi,
I installed rllab2 (for python 2.7 use of repository [py2 branch](https://github.com/rllab/rllab/tree/py2)) and all examples of examples folder, worked fine except trpo_gym.py.
I get this error when run trpo_gym.py :

```
Traceback (most recent call last):
  File "/home/amin/PycharmProjects/rllab2/rllab/envs/gym_env.py", line 9, in <module>
    from gym.wrappers.monitoring import logger as monitor_logger
ImportError: cannot import name logger
/home/amin/anaconda2/envs/rllab_snapshot/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
python /home/amin/PycharmProjects/rllab2/scripts/run_experiment_lite.py  --plot 'True'  --n_parallel '1'  --snapshot_mode 'last'  --exp_name 'experiment_2020_03_30_15_57_54_0001'  --seed '1'  --log_dir '/home/amin/PycharmProjects/rllab2/data/local/experiment/experiment_2020_03_30_15_57_54_0001'  --args_data 'Y2NvcHlfcmVnCl9yZWNvbnN0cnVjdG9yCnAxCihjcmxsYWIubWlzYy5pbnN0cnVtZW50ClN0dWJNZXRob2RDYWxsCnAyCmNfX2J1aWx0aW5fXwpvYmplY3QKcDMKTnRScDQKKGRwNQpTJ19fYXJncycKcDYKKGcxCihjcmxsYWIubWlzYy5pbnN0cnVtZW50ClN0dWJPYmplY3QKcDcKZzMKTnRScDgKKGRwOQpTJ2FyZ3MnCnAxMAoodHNTJ3Byb3h5X2NsYXNzJwpwMTEKY3JsbGFiLmFsZ29zLnRycG8KVFJQTwpwMTIKc1Mna3dhcmdzJwpwMTMKKGRwMTQKUydwbG90JwpwMTUKSTAxCnNTJ2Jhc2VsaW5lJwpwMTYKZzEKKGc3CmczCk50UnAxNwooZHAxOApnMTAKKHRzZzExCmNybGxhYi5iYXNlbGluZXMubGluZWFyX2ZlYXR1cmVfYmFzZWxpbmUKTGluZWFyRmVhdHVyZUJhc2VsaW5lCnAxOQpzZzEzCihkcDIwClMnZW52X3NwZWMnCnAyMQpnMQooY3JsbGFiLm1pc2MuaW5zdHJ1bWVudApTdHViQXR0cgpwMjIKZzMKTnRScDIzCihkcDI0ClMnX29iaicKcDI1CmcxCihnNwpnMwpOdFJwMjYKKGRwMjcKZzEwCih0c2cxMQpjcmxsYWIuZW52cy5ub3JtYWxpemVkX2VudgpOb3JtYWxpemVkRW52CnAyOApzZzEzCihkcDI5ClMnZW52JwpwMzAKZzEKKGc3CmczCk50UnAzMQooZHAzMgpnMTAKKHRzZzExCmNybGxhYi5lbnZzLmd5bV9lbnYKR3ltRW52CnAzMwpzZzEzCihkcDM0ClMnZW52X25hbWUnCnAzNQpTJ1BlbmR1bHVtLXYwJwpwMzYKc1MncmVjb3JkX3ZpZGVvJwpwMzcKSTAwCnNzYnNzYnNTJ19hdHRyX25hbWUnCnAzOApTJ3NwZWMnCnAzOQpzYnNzYnNTJ2JhdGNoX3NpemUnCnA0MApJNDAwMApzUydkaXNjb3VudCcKcDQxCkYwLjk4OTk5OTk5OTk5OTk5OTk5CnNTJ3N0ZXBfc2l6ZScKcDQyCkYwLjAxCnNTJ25faXRyJwpwNDMKSTUwCnNnMzAKZzI2CnNTJ3BvbGljeScKcDQ0CmcxCihnNwpnMwpOdFJwNDUKKGRwNDYKZzEwCih0c2cxMQpjcmxsYWIucG9saWNpZXMuZ2F1c3NpYW5fbWxwX3BvbGljeQpHYXVzc2lhbk1MUFBvbGljeQpwNDcKc2cxMwooZHA0OApnMjEKZzEKKGcyMgpnMwpOdFJwNDkKKGRwNTAKZzI1CmcyNgpzZzM4CmczOQpzYnNTJ2hpZGRlbl9zaXplcycKcDUxCihJOApJOAp0cDUyCnNzYnNTJ21heF9wYXRoX2xlbmd0aCcKcDUzCmcxCihnMjIKZzMKTnRScDU0CihkcDU1CmcyNQpnMjYKc2czOApTJ2hvcml6b24nCnA1NgpzYnNzYlMndHJhaW4nCnA1NwoodChkcDU4CnRwNTkKc1MnX19rd2FyZ3MnCnA2MAooZHA2MQpzYi4='
/home/amin/anaconda2/envs/rllab_snapshot/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
using seed 1
using seed 1
Traceback (most recent call last):
  File "/home/amin/PycharmProjects/rllab2/rllab/envs/gym_env.py", line 9, in <module>
    from gym.wrappers.monitoring import logger as monitor_logger
ImportError: cannot import name logger
/home/amin/anaconda2/envs/rllab_snapshot/lib/python2.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "/home/amin/PycharmProjects/rllab2/rllab/misc/instrument.py", line 1032, in concretize
    *args, **kwargs)
  File "/home/amin/PycharmProjects/rllab2/rllab/envs/gym_env.py", line 89, in __init__
    self._horizon = env.spec.tags['wrapper_config.TimeLimit.max_episode_steps']
AttributeError: 'EnvSpec' object has no attribute 'tags'
Traceback (most recent call last):
  File "/home/amin/PycharmProjects/rllab2/scripts/run_experiment_lite.py", line 115, in <module>
    run_experiment(sys.argv)
  File "/home/amin/PycharmProjects/rllab2/scripts/run_experiment_lite.py", line 102, in run_experiment
    maybe_iter = concretize(data)
  File "/home/amin/PycharmProjects/rllab2/rllab/misc/instrument.py", line 1014, in concretize
    obj = concretize(maybe_stub.obj)
  File "/home/amin/PycharmProjects/rllab2/rllab/misc/instrument.py", line 1029, in concretize
    kwargs = concretize(maybe_stub.kwargs)
  File "/home/amin/PycharmProjects/rllab2/rllab/misc/instrument.py", line 1044, in concretize
    ret[concretize(k)] = concretize(v)
  File "/home/amin/PycharmProjects/rllab2/rllab/misc/instrument.py", line 1029, in concretize
    kwargs = concretize(maybe_stub.kwargs)
  File "/home/amin/PycharmProjects/rllab2/rllab/misc/instrument.py", line 1044, in concretize
    ret[concretize(k)] = concretize(v)
  File "/home/amin/PycharmProjects/rllab2/rllab/misc/instrument.py", line 1022, in concretize
    obj = concretize(maybe_stub.obj)
  File "/home/amin/PycharmProjects/rllab2/rllab/misc/instrument.py", line 1029, in concretize
    kwargs = concretize(maybe_stub.kwargs)
  File "/home/amin/PycharmProjects/rllab2/rllab/misc/instrument.py", line 1044, in concretize
    ret[concretize(k)] = concretize(v)
  File "/home/amin/PycharmProjects/rllab2/rllab/misc/instrument.py", line 1038, in concretize
    ret = maybe_stub.__stub_cache
  File "/home/amin/PycharmProjects/rllab2/rllab/misc/instrument.py", line 155, in __getattr__
    raise AttributeError('Cannot get attribute %s from %s' % (item, self.proxy_class))
AttributeError: Cannot get attribute __stub_cache from <class 'rllab.envs.gym_env.GymEnv'>
2020-03-30 15:57:55.692711 +0430 | [experiment_2020_03_30_15_57_54_0001] observation space: Box(3,)
2020-03-30 15:57:55.693063 +0430 | [experiment_2020_03_30_15_57_54_0001] action space: Box(1,)
Error while instantiating <class 'rllab.envs.gym_env.GymEnv'>

Process finished with exit code 0
```

Any idea how I can fix this?

Thanks.

**Comment by leo2r** [comment]
Same error, has anyone figured out how to fix this? 🙏🏽
