### ISSUE TITLE
Error while running trpo_gym.py

### ISSUE THREAD

**Issue by sahiliitm** [rllab/rllab#42]
Hi,

I am trying to run examples/trpo_gym.py on a remote server. I get the following error log:

```

Using gpu device 0: Tesla K80 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 4004.)
python /home/iitm/sahil/rllab/scripts/run_experiment_lite.py  --n_parallel '1'  --snapshot_mode 'last'  --exp_name 'experiment_2016_09_29_02_46_48_0001'  --seed '1'  --log_dir '/home/iitm/sahil/rllab/data/local/experiment/experiment_2016_09_29_02_46_48_0001'  --args_data 'Y2NvcHlfcmVnCl9yZWNvbnN0cnVjdG9yCnAxCihjcmxsYWIubWlzYy5pbnN0cnVtZW50ClN0dWJNZXRob2RDYWxsCnAyCmNfX2J1aWx0aW5fXwpvYmplY3QKcDMKTnRScDQKKGRwNQpTJ19fYXJncycKcDYKKGcxCihjcmxsYWIubWlzYy5pbnN0cnVtZW50ClN0dWJPYmplY3QKcDcKZzMKTnRScDgKKGRwOQpTJ2FyZ3MnCnAxMAoodHNTJ3Byb3h5X2NsYXNzJwpwMTEKY3JsbGFiLmFsZ29zLnRycG8KVFJQTwpwMTIKc1Mna3dhcmdzJwpwMTMKKGRwMTQKUydiYXNlbGluZScKcDE1CmcxCihnNwpnMwpOdFJwMTYKKGRwMTcKZzEwCih0c2cxMQpjcmxsYWIuYmFzZWxpbmVzLmxpbmVhcl9mZWF0dXJlX2Jhc2VsaW5lCkxpbmVhckZlYXR1cmVCYXNlbGluZQpwMTgKc2cxMwooZHAxOQpTJ2Vudl9zcGVjJwpwMjAKZzEKKGNybGxhYi5taXNjLmluc3RydW1lbnQKU3R1YkF0dHIKcDIxCmczCk50UnAyMgooZHAyMwpTJ19vYmonCnAyNApnMQooZzcKZzMKTnRScDI1CihkcDI2CmcxMAoodHNnMTEKY3JsbGFiLmVudnMubm9ybWFsaXplZF9lbnYKTm9ybWFsaXplZEVudgpwMjcKc2cxMwooZHAyOApTJ2VudicKcDI5CmcxCihnNwpnMwpOdFJwMzAKKGRwMzEKZzEwCih0c2cxMQpjcmxsYWIuZW52cy5neW1fZW52Ckd5bUVudgpwMzIKc2cxMwooZHAzMwpTJ2Vudl9uYW1lJwpwMzQKUydJbnZlcnRlZFBlbmR1bHVtLXYxJwpwMzUKc3Nic3Nic1MnX2F0dHJfbmFtZScKcDM2ClMnc3BlYycKcDM3CnNic3Nic1MnYmF0Y2hfc2l6ZScKcDM4Ckk0MDAwCnNTJ2Rpc2NvdW50JwpwMzkKRjAuOTg5OTk5OTk5OTk5OTk5OTkKc1Mnc3RlcF9zaXplJwpwNDAKRjAuMDEKc1Mnbl9pdHInCnA0MQpJNTAKc2cyOQpnMjUKc1MncG9saWN5JwpwNDIKZzEKKGc3CmczCk50UnA0MwooZHA0NApnMTAKKHRzZzExCmNybGxhYi5wb2xpY2llcy5nYXVzc2lhbl9tbHBfcG9saWN5CkdhdXNzaWFuTUxQUG9saWN5CnA0NQpzZzEzCihkcDQ2CmcyMApnMQooZzIxCmczCk50UnA0NwooZHA0OApnMjQKZzI1CnNnMzYKZzM3CnNic1MnaGlkZGVuX3NpemVzJwpwNDkKKEk4Ckk4CnRwNTAKc3Nic1MnbWF4X3BhdGhfbGVuZ3RoJwpwNTEKZzEKKGcyMQpnMwpOdFJwNTIKKGRwNTMKZzI0CmcyNQpzZzM2ClMnaG9yaXpvbicKcDU0CnNic3NiUyd0cmFpbicKcDU1Cih0KGRwNTYKdHA1NwpzUydfX2t3YXJncycKcDU4CihkcDU5CnNiLg=='
Using gpu device 0: Tesla K80 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 4004.)
using seed 1
using seed 1
[2016-09-29 02:46:52,213] Making new env: InvertedPendulum-v1
2016-09-29 02:46:52.789599 IST | [experiment_2016_09_29_02_46_48_0001] Populating workers...
2016-09-29 02:46:52.789729 IST | [experiment_2016_09_29_02_46_48_0001] Populated
0%                          100%
[                              ][2016-09-29 02:46:52,993] Starting new video recorder writing to /home/iitm/sahil/rllab/data/local/experiment/experiment_2016_09_29_02_46_48_0001/gym_log/openaigym.video.0.24658.video000000.mp4
Xlib:  extension "GLX" missing on display ":99".
[2016-09-29 02:46:52,997] GLFW error: 65542, desc: GLX: GLX extension not found
Xlib:  extension "GLX" missing on display ":99".
Traceback (most recent call last):
  File "/home/iitm/sahil/rllab/scripts/run_experiment_lite.py", line 115, in <module>
    run_experiment(sys.argv)
  File "/home/iitm/sahil/rllab/scripts/run_experiment_lite.py", line 102, in run_experiment
    maybe_iter = concretize(data)
  File "/home/iitm/sahil/rllab/rllab/misc/instrument.py", line 1018, in concretize
    return method(*args, **kwargs)
  File "/home/iitm/sahil/rllab/rllab/algos/batch_polopt.py", line 250, in train
    paths = self.sampler.obtain_samples(itr)
  File "/home/iitm/sahil/rllab/rllab/algos/batch_polopt.py", line 32, in obtain_samples
    scope=self.algo.scope,
  File "/home/iitm/sahil/rllab/rllab/sampler/parallel_sampler.py", line 114, in sample_paths
    show_prog_bar=True
  File "/home/iitm/sahil/rllab/rllab/sampler/stateful_pool.py", line 142, in run_collect
    result, inc = collect_once(self.G, *args)
  File "/home/iitm/sahil/rllab/rllab/sampler/parallel_sampler.py", line 89, in _worker_collect_one_path
    path = rollout(G.env, G.policy, max_path_length)
  File "/home/iitm/sahil/rllab/rllab/sampler/utils.py", line 11, in rollout
    o = env.reset()
  File "/home/iitm/sahil/rllab/rllab/envs/normalized_env.py", line 54, in reset
    ret = self._wrapped_env.reset()
  File "/home/iitm/sahil/rllab/rllab/envs/gym_env.py", line 90, in reset
    return self.env.reset()
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 134, in reset
    self.monitor._after_reset(observation)
  File "/usr/local/lib/python2.7/dist-packages/gym/monitoring/monitor.py", line 267, in _after_reset
    self.video_recorder.capture_frame()
  File "/usr/local/lib/python2.7/dist-packages/gym/monitoring/video_recorder.py", line 105, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 185, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/mujoco/mujoco_env.py", line 112, in _render
    self._get_viewer().render()
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/mujoco/mujoco_env.py", line 121, in _get_viewer
    self.viewer.start()
  File "/usr/local/lib/python2.7/dist-packages/mujoco_py/mjviewer.py", line 168, in start
    raise Exception('glfw failed to initialize')
Exception: glfw failed to initialize
[2016-09-29 02:46:52,999] GLFW error: 65537, desc: The GLFW library is not initialized
[2016-09-29 02:46:52,999] GLFW error: 65537, desc: The GLFW library is not initialized
[2016-09-29 02:46:52,999] Could not close renderer for InvertedPendulum-v1: _type_ must have storage info
[2016-09-29 02:46:52,999] GLFW error: 65537, desc: The GLFW library is not initialized
[2016-09-29 02:46:52,999] GLFW error: 65537, desc: The GLFW library is not initialized
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/utils/closer.py", line 67, in close
    closeable.close()
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 200, in close
    self.render(close=True)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 176, in render
    return self._render(close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/mujoco/mujoco_env.py", line 106, in _render
    self._get_viewer().finish()
  File "/usr/local/lib/python2.7/dist-packages/mujoco_py/mjviewer.py", line 324, in finish
    glfw.destroy_window(self.window)
  File "/usr/local/lib/python2.7/dist-packages/mujoco_py/glfw.py", line 809, in destroy_window
    window_addr = ctypes.cast(ctypes.pointer(window),
TypeError: _type_ must have storage info
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/gym/utils/closer.py", line 67, in close
    closeable.close()
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 200, in close
    self.render(close=True)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 176, in render
    return self._render(close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/mujoco/mujoco_env.py", line 106, in _render
    self._get_viewer().finish()
  File "/usr/local/lib/python2.7/dist-packages/mujoco_py/mjviewer.py", line 324, in finish
    glfw.destroy_window(self.window)
  File "/usr/local/lib/python2.7/dist-packages/mujoco_py/glfw.py", line 809, in destroy_window
    window_addr = ctypes.cast(ctypes.pointer(window),
TypeError: _type_ must have storage info
```

Any idea what is happening? As far as I understand it, it is not able to render the game-frontend. However, since Im running this on a remote server, I do not mind not rendering the front end. How would I turn off rendering?

Thanks,

**Comment by dementrock** [comment]
Looking into this now.

**Comment by dementrock** [comment]
Can you try turning off video recording? Something like
```python
env = normalize(GymEnv("Pendulum-v0", record_video=False))
```

**Comment by sahiliitm** [comment]
Oh, that seems to be working. Thank you. :)
